# Project
repo_url: https://github.com/inventree/InvenTree.github.io
site_name: InvenTree Documentation
site_description: InvenTree - Open Source Inventory Management
site_author: InvenTree
google_analytics: ['UA-143467500-1', 'InvenTree.github.io']

# Theme
theme:
  name: material
  palette:
    scheme: slate
  logo: assets/logo.png
  favicon: assets/favicon.ico
  features:
    - instant
    - tabs
extra_css:
  - stylesheets/extra.css

# Navigation
nav:
  - Home: index.md
  - Contribute: contribute.md
  - Getting Started:
    - Installation: start/install.md
    - Configuration: start/config.md
    - Deploying: start/deploy.md
    - Updating: start/update.md
    - Migrating: start/migrate.md
  - Parts:
    - Parts: part/part.md
    - Part Views: part/views.md
    - Parameters: part/parameter.md
    - Template Parts: part/template.md
    - Tests: part/test.md
  - Stock:
    - Stock: 404.md
  - Build:
    - Build: 404.md
  - Buy:
    - Buy: 404.md
  - Report:
    - Report: 404.md
  - Admin:
    - Admin: 404.md
  - Extend:
    - Extend: 404.md

# Plugins
plugins:
  - search
  - macros:
      include_dir: _includes

# Extensions
markdown_extensions:
  - admonition
  - pymdownx.details
  - markdown.extensions.codehilite
  - toc:
      permalink: ⚓
